<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>O2Play</AssemblyName>
    <RootNamespace>O2Play</RootNamespace>
    <NuGetAudit>false</NuGetAudit>
    <NoWarn>$(NoWarn);NU1900</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.1.0" ExcludeAssets="native" />
    <PackageReference Include="ManagedBass" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\**\*" />
    <None Include="Libs\bass.dll">
      <Link>bass.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Libs\raylib.dll">
      <Link>raylib.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
